[package]
name = "vierysik"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
vulkano-win = { version = "0.29.0", features = ["winit_"] }
vulkano = "0.29.0"