name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 12
        style: mozilla
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: fieryzig
        author_email: duo0702@live.cn
        message: 'clang-format lint'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
